### ISSUE TITLE
pam_env: NULL dereference when /etc/environment contains a key without a value

### ISSUE THREAD

**Issue by freedge** [linux-pam/linux-pam#796]
as discovered on https://discussion.fedoraproject.org/t/sudo-crash-cant-access-sudo-segmentation-fault-core-dumped-fedora-40/117037
when /etc/environment is malformed (eg containing a single word, without = sign), pam cores with sigsegv:

```
Core was generated by `sudo su'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  econf_unescnl (val=0x0) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/modules/pam_env/pam_env.c:175
175         while (*p != '\0') {
(gdb) bt
#0  econf_unescnl (val=0x0) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/modules/pam_env/pam_env.c:175
#1  econf_read_file (pamh=pamh@entry=0x55f4e050d8f0, filename=filename@entry=0x0, delim=delim@entry=0x7fb20e0480f4 "=", name=name@entry=0x7fb20e048127 "environment",
    suffix=suffix@entry=0x7fb20e048175 "", subpath=subpath@entry=0x7fb20e048175 "", lines=0x7fff605a9360) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/modules/pam_env/pam_env.c:295
#2  0x00007fb20e0469bd in _parse_env_file (pamh=0x55f4e050d8f0, ctrl=0, file=0x0) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/modules/pam_env/pam_env.c:929
#3  handle_env (pamh=0x55f4e050d8f0, argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/modules/pam_env/pam_env.c:1058
#4  0x00007fb20dee9c0f in _pam_dispatch_aux (pamh=<optimized out>, flags=8, h=<optimized out>, resumed=<optimized out>, use_cached_chain=<optimized out>)
    at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/libpam/pam_dispatch.c:110
#5  _pam_dispatch (pamh=<optimized out>, flags=flags@entry=8, choice=choice@entry=2) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/libpam/pam_dispatch.c:426
#6  0x00007fb20deea4e3 in pam_setcred (pamh=<optimized out>, flags=flags@entry=8) at /usr/src/debug/pam-1.6.1-1.fc40.x86_64/libpam/pam_auth.c:68
#7  0x00007fb20d7901e1 in sudo_pam_begin_session (ctx=0x7fb20d80f460 <sudoers_ctx.lto_priv>, pw=0x55f4e0532790, user_envp=0x7fff605a9d98, auth=<optimized out>) at ./auth/pam.c:487
#8  0x00007fb20d793bb1 in sudo_auth_begin_session (ctx=<optimized out>, pw=0x55f4e0532790, user_env=0x7fff605a9d98) at ./auth/sudo_auth.c:435
#9  sudoers_policy_init_session (pwd=0x55f4e0532790, user_env=0x7fff605a9d98, errstr=0x7fff605a9690) at ./policy.c:1193
#10 0x000055f4deaa6ed3 in policy_init_session (details=0x7fff605a9ce0) at ./sudo.c:1432
#11 0x000055f4dea9bc79 in exec_pty (details=0x7fff605a9ce0, user_details=0x7fff605a9c70, evbase=0x55f4e04ff860, cstat=0x7fff605a9b80) at ./exec_pty.c:1102
#12 0x000055f4deaa660f in sudo_execute (details=0x7fff605a9ce0, user_details=0x7fff605a9c70, evbase=0x55f4e04ff860, cstat=0x7fff605a9b80) at ./exec.c:493
#13 run_command (command_details=command_details@entry=0x7fff605a9ce0, user_details=user_details@entry=0x7fff605a9c70) at ./sudo.c:1064
#14 0x000055f4dea8fe8f in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at ./sudo.c:302
```

this seems caused by recent commit https://github.com/linux-pam/linux-pam/commit/9e4e3e42554fc6344a0b20b42aafb48011e9b2c9#diff-1fd87b83dd11acae1bdfd09ccb3031861d3b2d90c7450b07979c9c4c45d6b798L170

that triggers what seems to be a bug (or incorrectly documented feature) in libeconf: https://github.com/openSUSE/libeconf/issues/208

**Comment by freedge** [comment]
problem persists
