### ISSUE TITLE
Failing to install pam_namespace.service to /usr/lib/systemd/system

### ISSUE THREAD

**Issue by sjd-xlnx** [linux-pam/linux-pam#863]
Hello,
I am building a custom installation, and I don't have any root access.

I have built libpam successfully, with local prefix, using `meson setup -Dprefix=/home/myuser/.local build`.
However, during installation it fails. It successfully installs everything in the `/home/myuser/.local/...` with the exception of the `pam_namespace.service`. I get this error...

```
Installing /proj/xirhdstaff1/stevend/projects/linux-pam/build/modules/pam_namespace/pam_namespace.service to /usr/lib/systemd/system
Installation failed due to insufficient permissions.
Attempt to use /bin/sudo to gain elevated privileges? [y/n] n
Traceback (most recent call last):
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/minstall.py", line 870, in run
    installer.do_install(datafilename)
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/minstall.py", line 554, in do_install
    self.install_data(d, dm, destdir, fullprefix)
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/minstall.py", line 628, in install_data
    if self.do_copyfile(fullfilename, outfilename, makedirs=(dm, outdir), follow_symlinks=i.follow_symlinks):
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/minstall.py", line 427, in do_copyfile
    self.copy2(from_file, to_file)
  File "/home/stevend/env-3.10.6/lib/python3.10/site-packages/mesonbuild/minstall.py", line 324, in copy2
    shutil.copy2(*args, **kwargs)
  File "/tool/pandora64/.package/python-3.10.6/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/tool/pandora64/.package/python-3.10.6/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/lib/systemd/system/pam_namespace.service'
```

I don't need pam_namespace.service, but I could not find an option to not install it.

Is there an option to not install pam_namespace.service, or maybe give it a fake install directory?

Thank.

**Comment by ldv-alt** [comment]
Could you try this patch, please?

```
diff --git a/meson.build b/meson.build
index 307fed0a..e8f13b71 100644
--- a/meson.build
+++ b/meson.build
@@ -334,10 +334,13 @@ if systemdunitdir == ''
   systemdunitdir = prefixdir / 'lib' / 'systemd' / 'system'
   systemd = dependency('systemd', required: false)
   if systemd.found()
-    systemdunitdir = systemd.get_variable(
+    systemdsystemunitdir = systemd.get_variable(
       pkgconfig: 'systemdsystemunitdir',
       default_value: systemdunitdir,
     )
+    if systemdsystemunitdir.startswith(prefixdir / '')
+      systemdunitdir = systemdsystemunitdir
+    endif
   endif
 endif
 
```

**Comment by sjd-xlnx** [comment]
Hi, first of all - thanks for the incredibly quick response !

Yes, the patch worked. Here's extract from the log...

```
Installing /path-to-file/projects/linux-pam/build/modules/pam_namespace/pam_namespace_helper to /home/myuser/.local/sbin
Installing /path-to-file/projects/linux-pam/build/modules/pam_namespace/pam_namespace.service to /home/myuser/.local/lib/systemd/system
```

Installation was successful. Thanks.
